# Set prefix to Ctrl-z
unbind C-b
set -g prefix C-z
# Set r to reload config
bind-key r source-file ~/.tmux.conf \; display-message "Configuration reloaded"
# Set Ctrl-a switch to last window
bind-key C-a last-window
# Set window and pane base index to 1
set-option -g base-index 1
setw -g pane-base-index 1
set -g visual-activity on
set -g default-terminal "xterm-256color"
set -as terminal-features ",xterm-ghostty:RGB"
set -g mouse on
set-window-option -g xterm-keys on
set-window-option -g monitor-activity on
# Key h j k l to jump between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Ctrl-h Ctrl-l move between windows
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+
# Split window
unbind %
bind | split-window -h
bind - split-window -v
# Styles the pane borders
set -g pane-border-style fg=green,bg=black
# Styles the active pane border. Helps when you have
set -g pane-active-border-style fg=white,bg=blue
# statusbar ----------------------------------------------------------
# # default statusbar colors
set -g status-style fg=white,bg=black
# default window title colors
set -g window-status-style fg=cyan,bg=default,dim
set -g window-status-current-style fg=white,bg=red,bright
# active window title colors
# command/message line colors
set -g message-style fg=white,bg=black,bright
# The status bar itself.
# Uses the battery script below to display battery remaining
# in the status bar.
set -g status-justify right
set -g status-left-length 30
set -g status-left "#[fg=green]Sess: #S #[fg=yellow]#I #[fg=cyan]#P"
set -g status-right "#[fg=cyan]%d %b %R"
# Title
set-option -g set-titles on
set-option -g set-titles-string '[#h] #S-#W #T '
set-window-option -g automatic-rename on
set-window-option -g window-status-format ' #I #W '
set -g window-status-style bold

# Copy and paste
#
# Pipe the current pane to a log file with Shift-H - Press Shift-H again to stop.
bind-key H pipe-pane -o "cat >>$HOME/#W-tmux.log" \; display-message "Toggled logging to $HOME/#W-tmux.log"

# Cursor shape
set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[5 q'

# Plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'

# Optional: Highly recommended for Fish users
set -g @plugin 'laktak/extrakto' 

# This ensures it uses the system clipboard for mouse selections too
set -g @yank_selection_mouse 'clipboard' 

# Initialize TPM (MUST be at the very bottom)
# Before we enable this, please run
# mkdir -p ~/.tmux/plugins && git clone https://github.com/tmux-plugins/tpm.git ~/.tmux/plugins/tpm
run '~/.tmux/plugins/tpm/tpm'

run-shell ~/.tmux/plugins/tmux-sensible/sensible.tmux

# Window key mode vi
set -g mode-keys vi
set-window-option -g mode-keys vi
